config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/users/elderly', to: 'users#elderly'
  resources :users, only: [:show, :new, :index, :create, :edit, :update] do
    resources :remedies, only: [:new, :index, :show, :edit]
  end
  resources :remedies, only: [:create, :index, :update] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]
  resources :categories, only: [:index, :show]
  get '/users/elderly', to: 'users#elderly'
  get '/signin', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  root 'sessions#home'
  get '/logout' => 'sessions#destroy'
  delete 'logout' => 'sessions#destroy'
  match '/auth/github/callback', to: 'sessions#create', via: [:get, :post]
end

app/models/remedy.rb
class Remedy < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    has_many :users, :through => :comments
    has_many :remedy_categories
    has_many :categories, :through => :remedy_categories
    validates :title, :description, presence: true
    validates :title, uniqueness: true
end

app/controllers/remedies_controller.rb
class RemediesController < ApplicationController

    #list of remedies
    def index
        if params[:user_id]
            @remedies = User.find(params[:user_id]).remedies
        else
            @remedies = Remedy.all
        end
    end

    #remedy show page
    def show
        @remedy = Remedy.find(params[:id])
    end

    #new remedy page
    def new
        #does not let a user make a remedy from another users account
        if params[:user_id].to_i != current_user.id
            redirect_to user_path(current_user), notice: "Can only make a new remedy from your own account."
        else
            @remedy = Remedy.new(user_id: params[:user_id])
        end
    end

    #handles creating a new remedy
    def create
        @remedy = Remedy.new(remedy_params)
        if @remedy.save
            redirect_to user_remedy_path(id: @remedy.id, user_id: current_user.id)
        else
            #will render new remedy form if not meeting all validations
            render :new
        end
    end

    #edit remedy page
    def edit
        #does not let a user edit a remedy from another users account
        if params[:user_id].to_i != current_user.id
            redirect_to user_path(current_user), notice: "Can only edit remedies you created."
        else
          @remedy = Remedy.find(params[:id])
        end
    end

    #handles updating remedy
    def update
        @remedy = Remedy.find(params[:id])
        @remedy.update(remedy_params)
        redirect_to user_remedy_path(id: @remedy.id, user_id: @remedy.user.id)
    end
    
    private

    def remedy_params
        params.require(:remedy).permit(:title, :description, :user_id, category_ids:[])
    end

end

app/views/remedies/_form.html.erb
<% if @remedy.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@remedy.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @remedy.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :title %>
<%= f.hidden_field :user_id %>
<%= f.text_field :title %>
<br/>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
<%= f.submit %>

app/views/remedies/edit.html.erb
<h2>Edit Your Remedy</h2>

<%= form_for @remedy  do |f| %>
  <%= render :partial => "form", :locals=>{:f=>f} %>
<% end %>

<h3>Back to your remedy <%= link_to "here", user_remedy_path(id: @remedy.id, user_id: @remedy.user.id)%></h3>

app/views/remedies/index.html.erb
<h2>List of all the Home Remedies!</h2>
<% @remedies.each do |remedy| %>
    <%= link_to "Show #{remedy.title}", user_remedy_path(id: remedy.id, user_id: remedy.user_id) %><br>
<% end %>
<br>
<%= link_to "List of Categories", categories_path %><br>
<br>
<%= link_to "Go to your account page", user_path(current_user) %>

app/views/remedies/new.html.erb
<h2>Post about a home remedy you know!</h2>

<%= form_for @remedy  do |f| %>
  <%= render :partial => "form", :locals=>{:f=>f} %>
<% end %>

<h3>Back to account page <%= link_to "here", user_path(current_user)%></h3>

app/views/remedies/show.html.erb
<h2><%= @remedy.title %></h2>
<p>Description: <%= @remedy.description%><p>
<h4>Categories: </h4>
<% @remedy.categories.each do |category| %>
    <%= link_to "#{category.name}", category_path(category) %>
<% end %>
<h4>Written by: <%= link_to "#{@remedy.user.username}", user_path(@remedy.user) %></h3>
<%= link_to "Edit Remedy", edit_user_remedy_path(id: @remedy.id, user_id: @remedy.user.id) %><br>
<br>
<%= link_to "New Comment", new_remedy_comment_path(@remedy) %><br>
<h3>Comments</h3>
<% @remedy.comments.each do |comment| %>
    <h4><%= link_to "#{comment.user.username}", user_path(comment.user) %> said <%= comment.content %></h4>
<% end %>
<h4>Back to list of remedies <%= link_to "here", remedies_path %></h4>