config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/users/elderly', to: 'users#elderly'
  resources :users, only: [:show, :new, :index, :create, :edit, :update] do
    resources :remedies, only: [:new, :index, :show, :edit]
  end
  resources :remedies, only: [:create, :index, :update] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]
  resources :categories, only: [:index, :show]
  get '/users/elderly', to: 'users#elderly'
  get '/signin', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  root 'sessions#home'
  get '/logout' => 'sessions#destroy'
  delete 'logout' => 'sessions#destroy'
  match '/auth/github/callback', to: 'sessions#create', via: [:get, :post]
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    has_many :remedies
    has_many :comments
    has_many :commented_remedies, :through => :comments, source: :remedy
    scope :elderly, -> { where("age >= 60") }
    validates :username, uniqueness: true
    validates :username, :first_name, :last_name, :age, :bio, presence: true
    validates :age, numericality: { greater_than: 0}
    validates :bio, length: { maximum: 500 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #if you are not signed in you can only view these pages.
    skip_before_action :verified_user, only: [:new, :create]
    
    #list of users
    def index
        @users = User.all
    end

    #user home pages
    def show
        @user = User.find(params[:id])
    end

    #new user page
    def new
        if session[:user_id] == nil
            @user = User.new
        else
            #if user is already signed in and trying to make an account will redirect to your account page.
            redirect_to user_path(User.find_by(id: current_user.id)), notice: "You already have an account!"
        end
    end

    #handles creating new account
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            #if user does not meet all validations will render new form
            render :new
        end
    end

    #list of elderly users
    def elderly
        @elderly = User.elderly
    end

    #edit user page
    def edit
        #will not users edit others users account
        if params[:id].to_i != current_user.id
            redirect_to user_path(current_user), notice: "Can only edit your own account."
        else
            @user = User.find(params[:id])
        end
    end

    #handles editing a user account
    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    private

    def user_params
        params.require(:user).permit(:username, :first_name, :last_name, :age, :bio, :password)
    end

end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :username %>
<%= f.text_field :username %>
<br/>
<%= f.label :first_name %>
<%= f.text_field :first_name %>
<br/>
<%= f.label :last_name %>
<%= f.text_field :last_name %>
<br/>
<%= f.label :age %>
<%= f.text_field :age %>
<br/>
<%= f.label :bio %>
<%= f.text_area :bio %>
<br/>
<%= f.label :password %>
<%= f.text_field :password %>

<%= f.submit %>

app/views/users/edit.html.erb
<h2>Edit your account</h2>
<% flash.each do |type, msg| %>
    <%= msg %>
<% end %>
<br>
<%= form_for @user  do |f| %>
  <%= render :partial => "form", :locals=>{:f=>f} %>
<% end %>

<%= link_to "Back to account page", user_path(@user) %>

app/views/users/elderly.html.erb
<h2>All the Elders!</h2>
<% @elderly.each do |elder| %>
    <%= link_to "#{elder.username}", user_path(elder) %><br>
<% end %>
<br>
<%= link_to "Back to all the users", users_path %>

app/views/users/index.html.erb
<h2>List of all the Users of the Site!</h2>
<% @users.each do |user| %>
    <%= link_to "#{user.username}", user_path(user) %><br>
<% end %>
<h4>Click <%= link_to "here", '/users/elderly' %> to see a list of all the elderly users.</h4>
<h4>Click <%= link_to "here", user_path(current_user) %> to go back to your account page.</h4>

app/views/users/new.html.erb
<h2>Sign up for an account on The Home Remedy Website!</h2>

<%= form_for @user  do |f| %>
  <%= render :partial => "form", :locals=>{:f=>f} %>
<% end %>

<h3>Already have an account? Sign in <%= link_to "here", '/signin' %></h3> 

app/views/users/show.html.erb
<% flash.each do |type, msg| %>
    <%= msg %>
<% end %>
<h4>Username: <%= @user.username %></h4>
<h4>First Name: <%= @user.first_name %></h4>
<h4>Last Name: <%= @user.last_name %></h4>
<h4>Age: <%= @user.age %></h4>
<p><%= @user.bio %><p>
<%= link_to "Edit your account", edit_user_path(@user) %>
<h2>Remedies You Have Posted</h2>
<% @user.remedies.each do |remedy| %>
    <%= link_to "#{remedy.title}", user_remedy_path(id: remedy.id, user_id: @user.id)%><br>
<% end %>
<h2>Remedies You Have Commented On</h2>
<% @user.comments.each do |comment| %>
    <%= "You said #{comment.content} on the remedy"%>
    <%= link_to "#{comment.remedy.title}", user_remedy_path(id: comment.remedy.id, user_id: @user.id)%><br>
    <br>
<% end %>
<%= link_to "Create a New Remedy", new_user_remedy_path(@user) %><br>
<%= link_to "See a list of all Remedies", remedies_path %><br>
<%= link_to "See a list of all Users", users_path %><br>
<%= link_to "Log Out", logout_path, method: "delete" %>